"""Renderer for a selected forecast and its known tariff schedule."""
from __future__ import annotations

import json


def render_issue_date_forecast(source: dict) -> str:
    """Render only issued predictions; historical actuals stay outside this view."""
    data = json.dumps(source, separators=(",", ":"), ensure_ascii=False).replace("<", "\\u003c")
    return HTML.replace("/* DATA */", "const D=" + data + ";")


HTML = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{font-family:Inter,Segoe UI,Arial,sans-serif;color:#213d50;background:#eef3f0}body{margin:0;padding:28px;max-width:1280px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.12em;color:#39705f}h1{margin:.25rem 0}p{line-height:1.5;color:#54706e}.cards,.peaks,.costs{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:14px;margin:22px 0}.card,section,.peak,.cost{background:#fff;border:1px solid #d7e2de;border-radius:14px;padding:18px;box-shadow:0 3px 14px #153e4210}.card span,.peak span,.cost span{font-size:12px;color:#5c7771}.card strong,.peak strong,.cost strong{display:block;font-size:22px;margin-top:6px}canvas{width:100%;height:400px;display:block}.legend{display:flex;gap:18px;font-size:13px}.dot{width:10px;height:10px;border-radius:50%;display:inline-block;margin-right:5px}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:9px;border-bottom:1px solid #e4ece8;text-align:right}th:first-child,td:first-child{text-align:left}@media(max-width:700px){body{padding:16px}.cards,.peaks,.costs{grid-template-columns:repeat(2,1fr)}canvas{height:290px}}</style>
<p class="eyebrow">FORECAST</p><h1 id="title"></h1><p id="subtitle"></p><div class="cards" id="cards"></div><section><h2>Predicted demand and electricity tariff</h2><p>Demand uses the left axis; the tariff known at issue time uses the right axis. The X axis shows Polish local time.</p><canvas id="chart" aria-label="Predicted electricity demand and tariff price"></canvas><div class="legend"><span><i class="dot" style="background:#e08a3c"></i>Predicted demand · kWh</span><span><i class="dot" style="background:#24716c"></i>Tariff · <span id="unit"></span>/kWh</span></div></section><section><h2>Forecast energy cost per 24-hour window</h2><p>Predicted consumption multiplied by the applicable tariff; this is an estimate, not a bill.</p><div class="costs" id="costs"></div></section><section><h2>Two highest predicted peaks per 24-hour window</h2><div class="peaks" id="peaks"></div></section><section class="table"><h2>Hourly forecast</h2><table><thead><tr><th>Polish local time</th><th>Predicted kWh</th><th>Tariff</th></tr></thead><tbody id="rows"></tbody></table></section><script>/* DATA */
const $=id=>document.getElementById(id),loadMax=Math.max(1,...D.forecast_kwh),priceMax=Math.max(1,...D.tariff_price),fmtTime=value=>new Date(value).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
$('title').textContent=`${D.horizon}-hour ${D.model}`;
$('subtitle').textContent=`Weather: ${D.weather}. Tariff: ${D.tariff_label}.`;
$('unit').textContent=D.currency;
$('cards').innerHTML=[['Selected model',D.model],['Horizon',D.horizon+' hours'],['Highest forecast',loadMax.toFixed(2)+' kWh'],['Tariff range',Math.min(...D.tariff_price).toFixed(2)+'–'+priceMax.toFixed(2)+' '+D.currency]].map(([k,v])=>`<div class="card"><span>${k}</span><strong>${v}</strong></div>`).join('');
$('costs').innerHTML=D.daily_costs.map(day=>`<article class="cost"><span>24-hour window ${day.window+1} · from ${fmtTime(day.start_local)}</span><strong>${Number(day.forecast_cost).toFixed(2)} ${D.currency}</strong></article>`).join('');
$('peaks').innerHTML=D.peaks.map((p,i)=>`<article class="peak"><span>24-hour window ${p.window+1} · peak ${(i%2)+1}</span><strong>${Number(p.forecast_kwh).toFixed(2)} kWh</strong><p>${fmtTime(p.timestamp_local)}</p></article>`).join('');
$('rows').innerHTML=D.timestamps.map((t,i)=>`<tr><td>${fmtTime(t)}</td><td>${D.forecast_kwh[i].toFixed(3)}</td><td>${D.tariff_price[i].toFixed(2)} ${D.currency}</td></tr>`).join('');
function draw(){const c=$('chart'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);const w=r.width,h=r.height,L=52,R=58,T=16,B=54,y=(v,max)=>h-B-v/max*(h-T-B);const line=(values,max,color)=>{x.strokeStyle=color;x.lineWidth=2.5;x.beginPath();values.forEach((v,i)=>{const px=L+i/Math.max(1,values.length-1)*(w-L-R);i?x.lineTo(px,y(v,max)):x.moveTo(px,y(v,max))});x.stroke()};x.fillStyle='#fff';x.fillRect(0,0,w,h);x.font='12px Inter';for(let i=0;i<5;i++){const yy=T+i*(h-T-B)/4;x.strokeStyle='#dce7e2';x.beginPath();x.moveTo(L,yy);x.lineTo(w-R,yy);x.stroke();x.fillStyle='#5c7771';x.fillText((loadMax*(1-i/4)).toFixed(1),4,yy+4);x.fillText((priceMax*(1-i/4)).toFixed(2),w-R+6,yy+4)}const labels=Math.min(6,D.timestamps.length);for(let j=0;j<labels;j++){const i=Math.round(j*(D.timestamps.length-1)/Math.max(1,labels-1)),px=L+i/Math.max(1,D.timestamps.length-1)*(w-L-R);x.strokeStyle='#dce7e2';x.beginPath();x.moveTo(px,h-B);x.lineTo(px,h-B+4);x.stroke();x.fillStyle='#5c7771';x.textAlign=j===0?'left':j===labels-1?'right':'center';x.fillText(fmtTime(D.timestamps[i]),px,h-12)}x.textAlign='left';line(D.forecast_kwh,loadMax,'#e08a3c');line(D.tariff_price,priceMax,'#24716c')}
addEventListener('resize',draw);draw();</script></html>'''
