"""Create an offline visual comparison of the 24-hour, 3-day and 7-day forecasts."""
import argparse
import json
from pathlib import Path
import pandas as pd

ROOT=Path(__file__).resolve().parent

HTML='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forecast architecture comparison</title>
<style>:root{font-family:Segoe UI,Arial,sans-serif;color:#243646;background:#f3f6f8}body{max-width:1300px;margin:24px auto;padding:0 24px}h1{margin-bottom:4px}.muted{color:#647789;line-height:1.45}.controls,section{background:#fff;border:1px solid #dbe3e8;border-radius:12px;padding:18px;margin:18px 0}.controls{display:flex;gap:18px;align-items:end;flex-wrap:wrap}.controls label{display:grid;gap:5px;font-size:13px}select{padding:8px;border:1px solid #bdcbd5;border-radius:5px;background:white}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:#fff;border:1px solid #dbe3e8;border-radius:10px;padding:15px}.card span{font-size:12px;color:#647789}.card b{display:block;font-size:23px;margin-top:7px}canvas{width:100%;height:360px;display:block}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:9px;border-bottom:1px solid #e4e9ee;text-align:right}th:first-child,td:first-child{text-align:left}th{background:#eef3f6}.legend{display:flex;gap:15px;flex-wrap:wrap;font-size:13px}.legend i{display:inline-block;width:12px;height:3px;margin-right:5px;vertical-align:middle;background:var(--c)}.note{border-left:4px solid #ca8344;padding:10px;background:#fff8f0;line-height:1.5}@media(max-width:700px){body{padding:0 10px}.cards{grid-template-columns:repeat(2,1fr)}}</style>
<h1>Forecast architecture comparison</h1><p class="muted">Synthetic household load. Recorded historical weather is used as a perfect forecast in this backtest.</p>
<div class="controls"><label>Forecast origin<select id="origin"></select></label><label>Visible horizon<select id="horizon"><option value="24">24 hours</option><option value="72">3 days</option><option value="168" selected>7 days</option></select></label></div>
<div class="cards" id="cards"></div><section><h2>Actual and forecast load</h2><p class="muted">kWh per physical hour. Every forecast is recursive: after the origin, models use their own previous predictions, never the future actual load.</p><canvas id="line"></canvas><div class="legend" id="legend"></div></section>
<section><h2>Modular model explanation</h2><p class="muted">The component model adds deterministic base demand, predicted behaviour demand, and predicted thermal demand. These are forecasts, not observed sub-meter readings.</p><canvas id="components" style="height:260px"></canvas><div class="legend" id="componentLegend"></div></section>
<section><h2>Rolling-origin evaluation</h2><p class="muted">MAE/RMSE are kWh per hour. WAPE and total error are percentages. Peak-hour MAE is the error at the actual peak. Peak timing is the absolute distance between predicted and actual peak hour.</p><div id="metrics"></div></section>
<section class="note"><b>Interpretation:</b> Architecture A needs separate historical meters for behaviour, heating and boiler to be trained/calibrated with real data. Architecture B needs only the total meter. Neither architecture should use future appliance energy, future occupancy, or future indoor temperature as a feature.</section>
<script>/* DATA */
const C={actual:'#253e5b',seasonal_naive:'#8998a5',direct_total_gbdt:'#c96d38',modular_component_gbdt:'#278a7b'}, N={actual:'Actual',seasonal_naive:'Seasonal naive',direct_total_gbdt:'Direct total model',modular_component_gbdt:'Modular component model'};const $=x=>document.getElementById(x);
function setup(){[...new Set(D.p.map(x=>x.origin_utc))].forEach(x=>$('origin').add(new Option(x,x)));$('origin').onchange=draw;$('horizon').onchange=draw;draw()}
function chart(id,series,labels){let c=$(id),r=c.getBoundingClientRect(),z=devicePixelRatio||1;c.width=r.width*z;c.height=r.height*z;let x=c.getContext('2d');x.scale(z,z);let w=r.width,h=r.height,L=54,R=18,T=18,B=35;let all=series.flatMap(s=>s.v),max=Math.max(1,...all),min=0,y=v=>h-B-(v-min)/(max-min)*(h-T-B);x.fillStyle='#fff';x.fillRect(0,0,w,h);for(let k=0;k<=4;k++){let yy=T+(h-T-B)*k/4;x.strokeStyle='#e4eaee';x.beginPath();x.moveTo(L,yy);x.lineTo(w-R,yy);x.stroke();x.fillStyle='#5e7182';x.font='12px Segoe UI';x.fillText((max-(max-min)*k/4).toFixed(1),4,yy+4)}series.forEach(s=>{x.strokeStyle=s.c;x.lineWidth=2;x.beginPath();s.v.forEach((v,i)=>{let px=L+i/Math.max(1,s.v.length-1)*(w-L-R);i?x.lineTo(px,y(v)):x.moveTo(px,y(v))});x.stroke()});for(let k=0;k<=4;k++){let i=Math.round(k*(labels.length-1)/4);x.fillStyle='#5e7182';x.fillText(labels[i].slice(5,16),L+i/Math.max(1,labels.length-1)*(w-L-R)-10,h-10)}}
function draw(){let origin=$('origin').value,H=+$('horizon').value,rows=D.p.filter(x=>x.origin_utc===origin&&x.horizon_h<=H),by={};rows.forEach(r=>(by[r.model_id]??=[]).push(r));let actual=by.direct_total_gbdt.map(x=>x.actual_kwh),series=[{v:actual,c:C.actual}];['seasonal_naive','direct_total_gbdt','modular_component_gbdt'].forEach(id=>series.push({v:by[id].map(x=>x.load_hat),c:C[id]}));chart('line',series,by.direct_total_gbdt.map(x=>x.timestamp_utc));$('legend').innerHTML=[{id:'actual'},...['seasonal_naive','direct_total_gbdt','modular_component_gbdt'].map(id=>({id}))].map(o=>`<span><i style="--c:${C[o.id]}"></i>${N[o.id]}</span>`).join('');let m=by.modular_component_gbdt,comp=[{v:m.map(x=>x.base_hat),c:'#657f9d'},{v:m.map(x=>x.behaviour_hat),c:'#ca8a45'},{v:m.map(x=>x.thermal_hat),c:'#278a7b'}];chart('components',comp,m.map(x=>x.timestamp_utc));$('componentLegend').innerHTML=['Base','Behaviour','Thermal'].map((n,i)=>`<span><i style="--c:${comp[i].c}"></i>${n}</span>`).join('');let chosen=D.m.filter(x=>x.bucket===({24:'hours_1_24',72:'hours_25_72',168:'hours_1_168'}[H]));$('metrics').innerHTML='<table><tr><th>Model</th><th>MAE</th><th>RMSE</th><th>WAPE</th><th>Total error</th><th>Peak-hour MAE</th><th>Peak timing</th></tr>'+chosen.map(x=>`<tr><td>${N[x.model_id]}</td><td>${x.mae_kwh.toFixed(3)}</td><td>${x.rmse_kwh.toFixed(3)}</td><td>${x.wape_pct.toFixed(1)}%</td><td>${x.total_error_pct.toFixed(1)}%</td><td>${x.peak_hour_mae_kwh.toFixed(3)}</td><td>${x.peak_timing_mae_h.toFixed(1)} h</td></tr>`).join('')+'</table>';let d=by.direct_total_gbdt,mod=by.modular_component_gbdt;$('cards').innerHTML=[['Actual total',actual.reduce((a,b)=>a+b,0).toFixed(1)+' kWh'],['Direct total',d.reduce((a,b)=>a+b.load_hat,0).toFixed(1)+' kWh'],['Modular total',mod.reduce((a,b)=>a+b.load_hat,0).toFixed(1)+' kWh'],['Actual peak',Math.max(...actual).toFixed(2)+' kWh']].map(x=>`<div class="card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
window.addEventListener('resize',draw);setup();</script></html>'''

def build(input_dir: Path):
    predictions=pd.read_csv(input_dir/'forecast_predictions.csv')
    metrics=pd.read_csv(input_dir/'forecast_metrics.csv')
    payload={'p':predictions.to_dict('records'),'m':metrics.to_dict('records')}
    target=input_dir/'forecast_dashboard.html'
    target.write_text(HTML.replace('/* DATA */','const D='+json.dumps(payload,separators=(',',':'))+';'),encoding='utf-8')
    print(target)

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input',type=Path,default=ROOT/'results/forecast')
    args=parser.parse_args();build(args.input)
